<div class="bg-white dark:bg-gray-900 p-6 rounded-2xl border border-gray-200/80 dark:border-gray-800 shadow-xs">
    <div class="flex flex-col md:flex-row items-start md:items-center justify-between gap-4 mb-6">
        <div><h3 class="text-base font-bold text-gray-900 dark:text-white flex items-center gap-2"><i class="fa-solid fa-award text-amber-500"></i>Report Key Product (Domestic Hero SKUs)</h3><p class="text-xs text-gray-500 dark:text-gray-400 mt-1">Rekapitulasi performa per Kategori Key Product (GUMMY, BOLI, MARSHMALLOW, EXTR, dll).</p></div>
        <div class="flex items-center gap-2"><select x-model="filters.channelKey" @change="calculateKeyProducts()" class="text-xs rounded-xl border border-gray-300 dark:border-gray-700 bg-gray-50 dark:bg-gray-800 text-gray-900 dark:text-white py-2 px-3"><option value="">- All Channel -</option><option value="GT">General Trade</option><option value="MT">Modern Trade</option><option value="OEM">OEM</option><option value="ECOM">E-Commerce</option><option value="YTI">YTI</option></select></div>
    </div>
    <div class="overflow-x-auto scrollbar-thin">
        <table class="w-full text-left text-xs border-collapse min-w-[2400px]">
            <thead class="bg-gray-100 dark:bg-gray-800 text-gray-700 dark:text-gray-300 font-bold tracking-wider border-b border-gray-300 dark:border-gray-700 text-center">
                <tr><th class="p-3 border-r border-gray-300 dark:border-gray-700 w-12" rowspan="2">No.</th><th class="p-3 border-r border-gray-300 dark:border-gray-700 min-w-[180px] text-left" rowspan="2">KEY PRODUCT</th><template x-for="(month, idx) in monthNames" :key="'key-'+month"><th class="p-2 border-r border-gray-300 dark:border-gray-700 text-center" :class="idx % 2 === 0 ? 'bg-sky-50/70 dark:bg-gray-800/80' : 'bg-gray-100/70 dark:bg-gray-800/40'" colspan="3" x-text="month"></th></template><th class="p-2 border-l-2 border-primary/40 bg-primary/10 text-center" colspan="3">TOTAL</th></tr>
                <tr class="bg-gray-50 dark:bg-gray-800 text-[10px]"><?php for ($i = 0; $i < 12; $i++): ?><th class="p-1.5 border-r border-gray-200 dark:border-gray-700 w-20 text-center">QTY (Kg)</th><th class="p-1.5 border-r border-gray-200 dark:border-gray-700 w-28 text-center">REVENUE (Rp)</th><th class="p-1.5 border-r border-gray-200 dark:border-gray-700 w-20 text-center">ASP/kg</th><?php endfor; ?><th class="p-1.5 border-r border-gray-200 dark:border-gray-700 w-20 text-center bg-primary/10 font-bold">QTY (Kg)</th><th class="p-1.5 border-r border-gray-200 dark:border-gray-700 w-28 text-center bg-primary/10 font-bold">REVENUE (Rp)</th><th class="p-1.5 border-r border-gray-200 dark:border-gray-700 w-20 text-center bg-primary/10 font-bold">ASP/kg</th></tr>
            </thead>
            <tbody class="divide-y divide-gray-200 dark:divide-gray-800 font-mono">
                <template x-for="(kp, idx) in keyProductsSummary" :key="kp.name"><tr :class="kp.name === 'GRAND TOTAL' ? 'bg-primary/10 dark:bg-primary/20 font-extrabold text-gray-900 dark:text-white' : 'hover:bg-gray-50 dark:hover:bg-gray-800/50'"><td class="p-2.5 text-center border-r border-gray-200 dark:border-gray-800" x-text="kp.name === 'GRAND TOTAL' ? '' : (idx + 1)"></td><td class="p-2.5 border-r border-gray-200 dark:border-gray-800 font-sans text-gray-900 dark:text-white" x-text="kp.name"></td><template x-for="col in metricCols" :key="'kp-'+col.m+'-'+col.k"><td class="p-2 text-right border-r border-gray-200 dark:border-gray-800" :class="col.k === 'asp' ? 'bg-gray-50/50 dark:bg-gray-800/40' : ''" x-text="col.k === 'qty' ? formatNumber(kp.monthly[col.m].qty) : col.k === 'rev' ? formatNumber(kp.monthly[col.m].revenue) : formatNumber(calculateASP(kp.monthly[col.m].revenue, kp.monthly[col.m].qty))"></td></template><td class="p-2.5 text-right border-l-2 border-primary/30 border-r border-gray-200 dark:border-gray-800 font-bold" x-text="formatNumber(kp.total_qty)"></td><td class="p-2.5 text-right border-r border-gray-200 dark:border-gray-800 font-bold text-emerald-600 dark:text-emerald-400" x-text="formatNumber(kp.total_revenue)"></td><td class="p-2.5 text-right font-bold text-amber-600 dark:text-amber-400" x-text="formatNumber(calculateASP(kp.total_revenue, kp.total_qty))"></td></tr></template>
            </tbody>
        </table>
    </div>
</div>